# Generated by Django 4.1 on 2023-07-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idigital38', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_uri',
            field=models.ImageField(null=True, upload_to='media/pics/events'),
        ),
    ]
