# Generated by Django 4.1 on 2023-07-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idigital38', '0004_alter_event_image_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='additional_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='image_uri',
            field=models.ImageField(blank=True, null=True, upload_to='pics/organizers'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='order',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
