# Generated by Django 4.1 on 2023-07-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idigital38', '0005_alter_organizer_additional_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
