# Generated by Django 4.1 on 2023-07-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('image_uri', models.ImageField(blank=True, null=True, upload_to='pics/organizers')),
                ('role', models.CharField(default='', max_length=100)),
                ('additional_role', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'organizer',
                'verbose_name_plural': 'organizers',
            },
        ),
    ]
