# Generated by Django 4.1 on 2023-09-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('contacts', models.CharField(default='', max_length=100)),
                ('organization', models.CharField(choices=[('Школа (Я ученик)', 'School'), ('Университет (Я студент)', 'University'), ('Предприятие (Я сотрудник компании)', 'Company')], default='Школа (Я ученик)', max_length=100)),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
            },
        ),
    ]
