# Generated by Django 4.1 on 2023-11-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='contacts',
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='participation_type',
            field=models.CharField(choices=[('Участник', 'Participant'), ('Партнер', 'Partner')], default='Участник', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sections',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
