# Generated by Django 4.1 on 2023-11-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='organization',
            field=models.CharField(choices=[('Школа (ученик)', 'School'), ('Университет, СПО (студент)', 'University'), ('Предприятие (сотрудник компании)', 'Company')], default='Школа (ученик)', max_length=100),
        ),
    ]
