# Generated by Django 4.1 on 2023-07-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_programme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmeday',
            name='place',
        ),
    ]
