# Generated by Django 4.1 on 2023-07-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_programme', '0002_remove_programmeday_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daytimetable',
            name='day',
        ),
        migrations.RemoveField(
            model_name='report',
            name='block',
        ),
        migrations.DeleteModel(
            name='DayBlock',
        ),
        migrations.DeleteModel(
            name='DayTimetable',
        ),
        migrations.DeleteModel(
            name='ProgrammeDay',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
