# Generated by Django 4.1 on 2023-07-30 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum_programme', '0003_remove_daytimetable_day_remove_report_block_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('place', models.CharField(default='', max_length=150)),
                ('moderators', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'day_block',
                'verbose_name_plural': 'day_blocks',
            },
        ),
        migrations.CreateModel(
            name='ProgrammeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'programme_day',
                'verbose_name_plural': 'programme_days',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('time_start', models.BigIntegerField(default=0)),
                ('speakers', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_block', to='forum_programme.dayblock')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
            },
        ),
        migrations.CreateModel(
            name='DayTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('time_start', models.BigIntegerField(default=0)),
                ('time_end', models.BigIntegerField(default=0)),
                ('moderators', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('speakers', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_day', to='forum_programme.programmeday')),
            ],
            options={
                'verbose_name': 'day_timetable',
                'verbose_name_plural': 'day_timetables',
            },
        ),
        migrations.AddField(
            model_name='dayblock',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_day', to='forum_programme.programmeday'),
        ),
    ]
