# Generated by Django 4.1 on 2023-08-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_programme', '0006_alter_daytimetable_time_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time_start',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
