# Generated by Django 4.1 on 2023-08-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_programme', '0007_alter_report_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time_start',
            field=models.BigIntegerField(default=0),
        ),
    ]
