# Generated by Django 4.1 on 2023-08-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_programme', '0008_alter_report_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='time_end',
            field=models.BigIntegerField(default=0),
        ),
    ]
