# Generated by Django 4.1 on 2023-11-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_programme', '0010_alter_report_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayblock',
            name='target_audience',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
